import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { AppKit } from "@/context/appkit";
import AppNavbar from "@/components/layouts/navbar/navbar";
import ContractProvider from "@/context/contract-provider";
import EventCreateModal from "@/components/event-create-modal/event-create-modal";
import type { Metadata } from "next";
import NftMintedModal from "@/components/nft-minted-modal/nft-minted-modal";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppKit>
          <ContractProvider>
            <AppNavbar />
            <EventCreateModal />
            <NftMintedModal />

            <Toaster />
            <main className="p-4">{children}</main>
          </ContractProvider>
        </AppKit>
      </body>
    </html>
  );
}
